=== ScilifelabDataCentre/data.scilifelab.se/schemas/data/services.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "/schemas/data/services.schema.json",
    "title": "Services Schema",
    "description": "Schema for validating service objects used in the data.scilifelab.se",
    "type": "array",
    "items": {
      "type": "object",
      "required": [
        "target",
        "type",
        "search_tags",
        "name",
        "description",
        "url",
        "maintained_by"
      ],
      "properties": {
        "target": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "researchers",
              "facilities"
            ]
          },
          "minItems": 1,
          "uniqueItems": true,
          "description": "Target audience for the service."
        },
        "type": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          },
          "minItems": 1,
          "uniqueItems": true,
          "description": "One or more categories describing the type of service."
        },
        "search_tags": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          },
          "minItems": 1,
          "uniqueItems": true,
          "description": "Search keywords associated with the service."
        },
        "name": {
          "type": "string",
          "minLength": 1,
          "description": "Title or name of the service."
        },
        "description": {
          "type": "string",
          "minLength": 1,
          "description": "Short description about the service."
        },
        "thumbnail": {
          "type": "string",
          "description": "OPTIONAL: Path to a thumbnail image for the service.",
          "pattern": "^\\/img\\/service_thumbnails\\/[^\\s]+\\.(jpg|jpeg|png|svg)$"
        },
        "thumbnail_border": {
          "type": "boolean",
          "description": "OPTIONAL: Whether to display a border around the thumbnail image.",
          "default": false
        },
        "url": {
          "type": "string",
          "description": "URL linking to the service.",
          "pattern": "^(https?:\\/\\/|\\/).+"
        },
        "maintained_by": {
          "type": "string",
          "minLength": 1,
          "description": "Name of the individual or organization that maintains the service."
        },
        "maintained_by_url": {
          "type": "string",
          "format": "uri",
          "description": "OPTIONAL: Web address of the maintaining organization or individual."
        },
        "support_email": {
          "type": "string",
          "format": "email",
          "description": "OPTIONAL: Email address to contact for support regarding the service."
        },
        "support_website": {
          "type": "string",
          "format": "uri",
          "description": "OPTIONAL: Website URL for service support or documentation."
        },
        "support_github": {
          "type": "string",
          "format": "uri",
          "description": "OPTIONAL: GitHub repository URL for the service."
        },
        "support_status": {
          "type": "string",
          "format": "uri",
          "description": "OPTIONAL: Status page URL for the service."
        },
        "support_slack": {
          "type": "string",
          "format": "uri",
          "description": "OPTIONAL: Slack channel or workspace URL for service support."
        },
        "data_source_type": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          },
          "uniqueItems": true,
          "description": "OPTIONAL: Type of data source associated with the service."
        },
        "ddls": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          },
          "uniqueItems": true,
          "description": "OPTIONAL: Scientific area of the services that are also data sources."
        },
        "disease_type": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          },
          "uniqueItems": true,
          "description": "OPTIONAL: Disease types associated with the services that are also data sources."
        }
      },
      "additionalProperties": false
    }
}

=== ScilifelabDataCentre/data.scilifelab.se/data/repositories.json
[
  {
    "target": ["researchers"],
    "type": ["genetics"],
    "ddls": ["Epidemiology & Biology of infection"],
    "search_tags": [
      "infectious",
      "disease",
      "influenza",
      "sequencing data",
      "emerging infectious diseases",
      "SARS-CoV-2",
      "COVID-19",
      "InfA",
      "InfB",
      "genetics",
      "genes",
      "GISAID"
    ],
    "name": "GISAID",
    "description": "A sequencing data repository emerging infectious diseases, including influenza and SARS-CoV-2. Registration is needed to access the data, and there are multiple conditions related to data sharing.",
    "thumbnail": "/img/service_thumbnails/figshare.jpg",
    "url": "https://www.gisaid.org/",
    "maintained_by": "SciLifeLab Data Centre",
    "maintained_by_url": "https://scilifelab.se/data",
    "support_email": "figshare@scilifelab.se",
    "support_website": "https://scilifelab.se/data/repository"
  },
  {
    "target": ["researchers"],
    "type": ["tool"],
    "ddls": [
      "Epidemiology & Biology of infection",
      "precision med",
      "cell & molecular"
    ],
    "search_tags": [
      "SciLifeLab Serve",
      "AI",
      "Artificial intelligence",
      "Apps",
      "DASH",
      "R-Shiny",
      "Hosting",
      "Data sharing",
      "Machine learning",
      "NBIS",
      "SciLifeLab",
      "Data Centre"
    ],
    "name": "SciLifeLab Serve",
    "description": "Platform for sharing machine learning models and data science applications, such as Shiny and Dash apps.",
    "url": "https://serve.scilifelab.se/",
    "maintained_by": "SciLifeLab Data Centre",
    "maintained_by_url": "https://scilifelab.se/data",
    "support_email": "serve@scilifelab.se",
    "support_website": "https://serve.scilifelab.se/user_guide"
  },
  {
    "target": ["researchers"],
    "type": ["Storage resources"],
    "ddls": ["Epidemiology & Biology of infection"],
    "search_tags": ["FAIR Storage", "SUPR", "SciLifeLab", "Data Centre"],
    "name": "FAIR storage",
    "description": "Details about how researchers, research groups, and organisations can store their data using SciLifeLab FAIR Storage resources.",
    "url": "/services/fairstorage/",
    "thumbnail": "/img/service_thumbnails/fairstorage.jpg",
    "maintained_by": "SciLifeLab Data Centre",
    "maintained_by_url": "https://scilifelab.se/data",
    "support_email": "FAIRstorage@scilifelab.se"
  },
  {
    "target": ["researchers"],
    "type": ["portal"],
    "ddls": ["Epidemiology & Biology of infection"],
    "search_tags": [
      "Pathogens portal",
      "Pandemic preparedness portal",
      "COVID-19",
      "SciLifeLab",
      "Data Centre",
      "Tool"
    ],
    "name": "Swedish Pathogens Portal",
    "description": "Facilitates the sharing and promotion of pandemic preparedness and infectious disease data",
    "thumbnail": "/img/service_thumbnails/portal.jpg",
    "url": "https://pathogens.se/",
    "maintained_by": "SciLifeLab Data Centre",
    "maintained_by_url": "https://scilifelab.se/data",
    "support_email": "pathogens@scilifelab.se",
    "support_github": "https://github.com/ScilifelabDataCentre/covid-portal/tree/develop",
    "support_status": "https://status.dc.scilifelab.se/793602036"
  },
  {
    "target": ["researchers"],
    "type": ["portal", "helpdesk"],
    "ddls": ["Epidemiology & Biology of infection"],
    "search_tags": [
      "RDM",
      "Research data management",
      "Guidelines",
      "Helpdesk",
      "Portal",
      "NBIS",
      "SciLifeLab",
      "Data Centre"
    ],
    "name": "SciLifeLab RDM Guidelines",
    "description": "A portal containing information on research data management in Sweden",
    "thumbnail": "/img/service_thumbnails/rdm.jpg",
    "url": "https://data-guidelines.scilifelab.se",
    "maintained_by": "NBIS, SciLifeLab Data Centre",
    "support_email": "data-management@scilifelab.se",
    "support_website": "https://data-guidelines.scilifelab.se/contact/",
    "support_github": "https://github.com/ScilifelabDataCentre/RDM-guidelines",
    "support_status": "https://status.dc.scilifelab.se/793602117"
  },
  {
    "target": ["researchers"],
    "type": ["Database", "Portal", "Tool"],
    "ddls": [
      "Epidemiology & Biology of infection",
      "precision med",
      "cell & molecular"
    ],
    "search_tags": [
      "NBIS",
      "Metabolic Atlas",
      "GEM",
      "genome",
      "genes",
      "models",
      "reactions",
      "metabolites",
      "metatlas",
      "genome-scale",
      "enzyme",
      "turnover",
      "kcat"
    ],
    "name": "Metabolic Atlas",
    "description": "Metabolic Atlas is a web platform integrating open-source genome scale metabolic models (GEMs) for easy browsing and analysis.",
    "url": "https://metabolicatlas.org/",
    "thumbnail": "/img/service_thumbnails/metatlas.jpg",
    "maintained_by": "NBIS",
    "maintained_by_url": "http://www.nbis.se/",
    "support_email": "contact@metabolicatlas.org"
  }
]
