=== ScilifelabDataCentre/data.scilifelab.se/schemas/data/open_science/glossary.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "/schemas/data/open_science/glossary.schema.json",
    "title": "Open Science glossary schema",
    "description": "Schema for validating glossary objects used in the open science section of data.scilifelab.se",
    "type": "array",
    "items": {
      "type": "object",
      "required": [
        "term",
        "definition",
        "source",
        "source_name"
      ],
      "properties": {
        "term": {
          "type": "string",
          "minLength": 1,
          "description": "Title/name of the glossary."
        },
        "definition": {
          "type": "string",
          "minLength": 1,
          "description": "Short description about the glossary."
        },
        "source": {
          "type": "string",
          "description": "URL linking to the glossary.",
          "pattern": "^(https?:\\/\\/|\\/).+"
        },
        "source_name": {
          "type": "string",
          "minLength": 1,
          "description": "Short title to be used for hyperlink text of the glossary."
        },
        "image": {
          "type": "string",
          "description": "Path to a image for the glossary.",
          "pattern": "^\\/img\\/open_science\\/glossary\\/[^\\s]+\\.(jpg|jpeg|png|svg)$"
        },
        "image_alt": {
          "type": "string",
          "minLength": 1,
          "description": "Alt text for the provided image of the glossary."
        }
      },
      "additionalProperties": false
    }
}

=== ScilifelabDataCentre/data.scilifelab.se/data/open_science/glossary.json
[
  {
    "term": "UNESCO Open Science Definition",
    "definition": "An inclusive construct that combines various movements and practices aiming to make multilingual scientific knowledge openly available, accessible and reusable for everyone, to increase scientific collaborations and sharing of information for the benefits of science and society, and to open the processes of scientific knowledge creation,  evaluation and communication to societal actors beyond the traditional scientific community",
    "source": "https://www.unesco.org/en/legal-affairs/recommendation-open-science",
    "source_name": "Definition Source",
    "image": "/img/open_science/glossary/open_science_def.png"
  },
  {
    "term": "FAIR Principles",
    "definition": "FAIR is a framework designed to enhance the Findability, Accessibility, Interoperability, and Reusability of digital objects, comprising 15 guiding principles that ensure data and metadata are effectively managed and shared. It prioritises machine-actionability, ensuring that computational systems can efficiently find, access, interoperate, and reuse data with minimal human intervention. A key aspect of FAIR is the use of persistent identifiers (e.g., ORCID iDs, DOIs, RORs, RRIDs, RAiDs). High-quality metadata is essential in this framework, providing rich contextual information that enables accurate data discovery, integration, and reuse. The FAIR principles emphasise that data and metadata should be well-structured, openly accessible where possible, and supported by standardised formats and vocabularies to maximise interoperability and reusability. By implementing these principles, FAIR enables seamless data sharing and integration, supporting the computational nature of modern research.",
    "source": "https://www.gofair.foundation/interpretation",
    "source_name": "GO FAIR Principles and Interpretation"
  }
]
